### ISSUE TITLE
Bildestørrelse i grid

### ISSUE THREAD

**Issue by lokaltobias** [lokaltbyraa/lokaltbyraa.github.io#2]
To små problemer her:
1) Bildene blir mindre og mindre av en eller annen grunn?
2) kan ikke justere bildestørrelse i grid. Usikker på om dette egentlig er nødvendig, om det ikke skal brukes kan vi likegreit fjerne det fra koden 📝 

![Skjermbilde 2024-08-06 kl  10 51 51](https://github.com/user-attachments/assets/2fa8c0ee-8492-495e-9c78-0c8bd4bd19e8)

<ImageGrid>

    <ArticleImage 
    imagePath="nettside.jpg"
    altText="Alt"
    caption="Ivrig bygging på havnefronten"
    sizeSML="m"
    />

    <ArticleImage 
    imagePath="nettside.jpg"
    altText="Alt"
    caption="Installasjon"
    sizeSML="m"
    />

    <ArticleImage 
    imagePath="nettside.jpg"
    altText="Alt"
    caption="Juryen på vift"
    sizeSML="l"
    />

</ImageGrid>

**Comment by lokaltbyraa** [comment]
Bildegrid-modulen er fiksa sånna at bildene blir mindre og mindre. Merk at per nå kan vi ikke ha ulik bredde på bildene. Om det blir et behov senere kan jeg se på en løsning for ulik bildebredde.

Ref å oppgi størrelse på bilder i grid. Det er null problem å ikke ha det med i bildene. Som du kan se i koden til articleImage.astro så er sizeSML valgfri å oppgi (markert med “?”). Om det ikke er oppgitt noen verdi for size så settes det default til medium (se markeringa). DVS at vi trenger bare å oppgi size i artikkelbildene om bildet skal være større eller mindre enn vanlig avsnittsbredde.

![Skjermbilde 2024-08-09 kl  15 42 48](https://github.com/user-attachments/assets/ae0c570f-6701-4d27-9e8b-a249d665da76)
